[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "st"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bottle>=0.12.25",
    "gunicorn>=26.2.0",
]

[project.scripts]
st = "main:main"

[tool.hatch.build.targets.wheel]
packages = ["."]


